<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'User\Module'                     => __DIR__ . '/Module.php',
    'User\Controller\IndexController' => __DIR__ . '/src/User/Controller/IndexController.php',
    'User\Entity\User'                => __DIR__ . '/src/User/Entity/User.php',
    'User\Form\Login'                 => __DIR__ . '/src/User/Form/Login.php',
);
