<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Phpwisdom\User\Module'                     => __DIR__ . '/Module.php',
    'Phpwisdom\User\Controller\IndexController' => __DIR__ . '/src/User/Controller/IndexController.php',
    'Phpwisdom\User\Form\Login'                 => __DIR__ . '/src/User/Form/Login.php',
);
